### ISSUE TITLE
Ship style sheet to diffpy package

### ISSUE THREAD

**Issue by RomanMatthew** [Billingegroup/mpl-stylesheets#1]
Figure out group style sheets in general.

**Comment by sbillinge** [comment]
some thoughts that came up: (a) expose style sheet at a URL (b) release somehow so it can be included as a dependency, like a software package.

**Comment by CJ-Wright** [comment]
I think both would be good, I like the idea of the hard copy as a backup

**Comment by sbillinge** [comment]
closed by #2
