### ISSUE TITLE
plot a gallery of the colors in bg_style readme

### ISSUE THREAD

**Issue by sbillinge** [Billingegroup/mpl-stylesheets#11]
@dragonyanglong would it also be possible to plot the ``bg_style`` colors in the readme?  I think code to do it could be stolen from here:
https://matplotlib.org/3.1.0/gallery/color/named_colors.html
so it could be quick.   It would certainly be very useful.  For the label for each color, maybe just give its number in the color list?

**Comment by dragonyanglong** [comment]
done. please see my PR.
